### ISSUE TITLE
Can I use an empty api_key when using the Qwen model since it's a private API, so I haven't configured an access_key?

### ISSUE THREAD

**Issue by juemingai** [leoleelxh/ComfyUI-LLMs#6]
I am using the Qwen2-VL model, and this model is deployed on my local server, so I don't have a vision_key_ali. When I configure it as vision_key_ali: or vision_key_ali: "", it throws an error.
![image](https://github.com/user-attachments/assets/813461b6-74c3-465e-9423-aa3cc8ea5a79)

**Comment by leoleelxh** [comment]
In this scenario, this plugin is currently not supported
